sudo ./shine \
  --servers localhost \
  --threads 4 \
  --coroutines 4 \
  --data-path /data/xjs/random_dataset/1024dim100K/ \
  --query-suffix test \
  --ef-search 100 \
  --ef-construction 200 \
  --k 10 \
  --m 32 \
  --store-index \
  --initiator