servers = 192.168.6.202:1234 192.168.6.202:1235 192.168.6.202:1236 192.168.6.202:1237 192.168.6.202:1238
initiator = true
port = 1234
threads = 4
coroutines = 4
dim = 1024
k = 10
R = 64
beam-width = 32
beam-width-construction = 400
alpha = 1.2
search-mode = rabitq_gpu
; search-mode = exact_gpu
rabitq-bits = 4
gpu-device = 0
max-vectors = 75000000
cn-memory = 50
mn-memory = 50
cache = true
cache-ratio = 5
disable-thread-pinning = false
dim = 1024
load-index = true
index-prefix = /data/xjs/index/dvstor_index/1024dim50M
gpudirect-rdma = true
gpu-rabitq-cache-mb = 100
; gpu-rabitq-cache-mb = 100
neighbor-cache-mb = 0
